# Generated by Django 5.1.6 on 2025-02-26 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_discount_tax_alter_item_price_itemorder_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemorder',
            options={'default_related_name': '%(class)ss', 'verbose_name': 'Товар к заказу', 'verbose_name_plural': 'Товары к заказам'},
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='size',
            new_name='amount_off',
        ),
        migrations.RenameField(
            model_name='tax',
            old_name='size',
            new_name='percentage',
        ),
        migrations.AddField(
            model_name='discount',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='tax',
            name='description',
            field=models.CharField(default='VAT', max_length=16, verbose_name='Описание налога'),
        ),
        migrations.AddField(
            model_name='tax',
            name='display_name',
            field=models.CharField(default='VAT', max_length=16, verbose_name='Аббривиатура налога'),
        ),
        migrations.AddField(
            model_name='tax',
            name='inclusive',
            field=models.BooleanField(default=True, verbose_name='Включен?'),
        ),
    ]
