# Generated by Django 5.1.6 on 2025-03-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_itemorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма заказа'),
        ),
    ]
